### ISSUE TITLE
Error creating new sync rule

### ISSUE THREAD

**Issue by ruffzy** [lcdservices/JomSocial-Group-Sync#1]
Joomla 1.7, JomSocial 2.2.4
After clicking save in the create dialog I get this:

500 - An error has occurred.
/home/hitchch/www/2011.hceinsiedeln.ch/components/com_community/models/groups.php:895

Return to Control Panel

Call stack
# Function    Location

1   JAdministrator->dispatch()  /home/hitchch/www/2011.hceinsiedeln.ch/administrator/index.php:47
2   JComponentHelper::renderComponent() /home/hitchch/www/2011.hceinsiedeln.ch/administrator/includes/application.php:153
3   require_once()  /home/hitchch/www/2011.hceinsiedeln.ch/libraries/joomla/application/component/helper.php:156
4   JController->execute()  /home/hitchch/www/2011.hceinsiedeln.ch/administrator/components/com_jomsocialgroupsync/jomsocialgroupsync.php:23
5   JControllerForm->save() /home/hitchch/www/2011.hceinsiedeln.ch/libraries/joomla/application/component/controller.php:679
6   JModelAdmin->save() /home/hitchch/www/2011.hceinsiedeln.ch/libraries/joomla/application/component/controllerform.php:567
7   JDispatcher->trigger()  /home/hitchch/www/2011.hceinsiedeln.ch/libraries/joomla/application/component/modeladmin.php:864
8   JEvent->update()    /home/hitchch/www/2011.hceinsiedeln.ch/libraries/joomla/event/dispatcher.php:115
9   call_user_func_array()  /home/hitchch/www/2011.hceinsiedeln.ch/libraries/joomla/event/event.php:48
10  plgSystemJomSocialGroupSync->onContentAfterSave()  
11  CCachingModel->getMembers() /home/hitchch/www/2011.hceinsiedeln.ch/plugins/system/jomsocialgroupsync/jomsocialgroupsync.php:122
12  CCachingModel->__call() /home/hitchch/www/2011.hceinsiedeln.ch/plugins/system/jomsocialgroupsync/jomsocialgroupsync.php:122
13  call_user_func_array()  /home/hitchch/www/2011.hceinsiedeln.ch/components/com_community/libraries/core.php:2093
14  CommunityModelGroups->getMembers()  
15  CError->assert()    /home/hitchch/www/2011.hceinsiedeln.ch/components/com_community/models/groups.php:895
16  JError::raiseError()    /home/hitchch/www/2011.hceinsiedeln.ch/components/com_community/libraries/error.php:39
17  JError::raise() /home/hitchch/www/2011.hceinsiedeln.ch/libraries/joomla/error/error.php:215

When I try then to open the component page (list of all sync rules) I get:

500 - An error has occurred.
JDatabaseMySQL::query: 1064 - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 1 SQL=SELECT name FROM uehtm_community_groups WHERE id =

Return to Control Panel

Call stack
# Function    Location

1   JAdministrator->dispatch()  /home/hitchch/www/2011.hceinsiedeln.ch/administrator/index.php:47
2   JComponentHelper::renderComponent() /home/hitchch/www/2011.hceinsiedeln.ch/administrator/includes/application.php:153
3   require_once()  /home/hitchch/www/2011.hceinsiedeln.ch/libraries/joomla/application/component/helper.php:156
4   JController->execute()  /home/hitchch/www/2011.hceinsiedeln.ch/administrator/components/com_jomsocialgroupsync/jomsocialgroupsync.php:23
5   JomSocialGroupSyncController->display() /home/hitchch/www/2011.hceinsiedeln.ch/libraries/joomla/application/component/controller.php:679
6   JController->display()  /home/hitchch/www/2011.hceinsiedeln.ch/administrator/components/com_jomsocialgroupsync/controller.php:32
7   JomSocialGroupSyncViewSynchronizationrules->display()   /home/hitchch/www/2011.hceinsiedeln.ch/libraries/joomla/application/component/controller.php:645
8   JView->display()    /home/hitchch/www/2011.hceinsiedeln.ch/administrator/components/com_jomsocialgroupsync/views/synchronizationrules/view.html.php:40
9   JView->loadTemplate()   /home/hitchch/www/2011.hceinsiedeln.ch/libraries/joomla/application/component/view.php:180
10  include()   /home/hitchch/www/2011.hceinsiedeln.ch/libraries/joomla/application/component/view.php:582
11  JomSocialGroupSyncHelper::getJSGroupName()  /home/hitchch/www/2011.hceinsiedeln.ch/administrator/components/com_jomsocialgroupsync/views/synchronizationrules/tmpl/default.php:110
12  JDatabase->loadResult() /home/hitchch/www/2011.hceinsiedeln.ch/administrator/components/com_jomsocialgroupsync/helpers/jomsocialgroupsync.php:69
13  JDatabaseMySQLi->query()    /home/hitchch/www/2011.hceinsiedeln.ch/libraries/joomla/database/database.php:1008
14  JError::raiseError()    /home/hitchch/www/2011.hceinsiedeln.ch/libraries/joomla/database/database/mysqli.php:535
15  JError::raise() /home/hitchch/www/2011.hceinsiedeln.ch/libraries/joomla/error/error.php:215

On the concerning system I have had installed earlier versions before... but uninstalled before installing 9c8ebdc.

**Comment by lcdservices** [comment]
can you uninstall the component and plugin, then delete the database table called: #__jomsocialgroupsync_rules
yours would be: uehtm_jomsocialgroupsync_rules

we don't remove the table during uninstall, and don't modify the existing table on reinstall. i think the earlier version you installed has different field names than the final version. once that table is removed, reinstall and test.

**Comment by ruffzy** [comment]
The wrong mysql table was indeed the problem.
