### ISSUE TITLE
Creation of new content category fails when system plugin is enabled

### ISSUE THREAD

**Issue by ruffzy** [lcdservices/JomSocial-Group-Sync#2]
As soon as the system plugin is enabled the creation of a new content category creates this error:

Fatal error: Call to a member function getProperties() on a non-object in /home/hitchch/www/2011.hceinsiedeln.ch/libraries/joomla/application/component/modeladmin.php on line 622

This bug is also concerning the JomSocial plugins - these plugins need also to be deactivated before a new content category is created.

**Comment by lcdservices** [comment]
this is fixed. please download the latest package.
note -- you can install on top of your existing installation.
