### ISSUE TITLE
Group Sync working with ACL but member not admitted to JomSocial Group

### ISSUE THREAD

**Issue by ShaunP** [lcdservices/JomSocial-Group-Sync#7]
The problem is that when a user is approved to join a group, from the front end, their Joomla ACL is upgraded but they do not get joined to the JomSocial Group.

If you log in and go to ourworldschool.org/index.php/jomsocial  you will see that "pattytest, jilltest joined the group test3"  in the Recent Activities section (they were successfully upgraded to "Author"), but if you go to the group's members they are not present, and if pattytest/pattytest logs in, she cannot  access  group test3. 

Log into group test3 with abbynormal/abbynormal and see she is not here.

This is a fresh test site . I installed only:

Joomla 2.5.4
JomSocial 2.2.4
JomSocialGroupSync latest version (no hacks)
Gantry template v3.2.19
RocetTheme Tachyon Template latest version
JCE Editor 2.0.21
Akeeba 3.4.3 

Call if you need back end access: 203-722-0233

Thanks,
Shaun

**Comment by lcdservices** [comment]
fixed with commit: 88a60b85460fc55ac2c4d3e31f3eeb20697aa2d3
tagged: beta3
